[신동현] Assignment 1 | Project Layered pattern 적용
wecode-bootcamp-korea/47-backend-westagram-2 pull request #17
Opened 2023-06-19 05:37 UTC by donghyeun02

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)
Layered pattern 적용
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
<img width="973" alt="스크린샷 2023-06-19 오후 2 35 11" src="https://github.com/wecode-bootcamp-korea/47-backend-westagram-2/assets/129716523/a71459b6-75bc-41c1-8c93-272c712ea9e9">

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-06-19 10:10 UTC, Kang-kyunghun requested changes

2023-06-19 10:10 UTC, Kang-kyunghun commented on donghyeun/app.js
> +const http = require("http");
```suggestion
```

2023-06-19 10:10 UTC, Kang-kyunghun commented on donghyeun/app.js
> +const server = http.createServer(app);
http 모듈은 굳이 사용하지 않으셔도 됩니다.
```suggestion
```

2023-06-19 10:10 UTC, Kang-kyunghun commented on donghyeun/controllers/postController.js
> +const Upload = async (req, res) => {
- 변수명은 카멜케이스로 지어주세요.
- 함수에 대한 변수명(함수명)은 동사형으로 지어주되 목적(대상)까지 나타낼 수 있게 해주면 좋을 것 같습니다. 전체적으로 함수명은 한 번 더 살펴봐 주세요.
```suggestion
const createPost = async (req, res) => {
```

2023-06-19 10:10 UTC, Kang-kyunghun commented on donghyeun/controllers/postController.js
> +const All = async (req, res) => {
```suggestion
const getAllPost = async (req, res) => {
```

2023-06-19 10:10 UTC, Kang-kyunghun commented on donghyeun/controllers/postController.js
> +const User = async (req, res) => {
```suggestion
const getUserPost = async (req, res) => {
```

2023-06-19 10:10 UTC, Kang-kyunghun commented on donghyeun/controllers/userController.js
> +  }
```suggestion
  const { name, email, password, phoneNumber, profileImage } = req.body;
  
  if (!name || !email || !password || !phoneNumber || !profileImage) {
    return res.status(400).json({ message: "KEY_ERROR" });
  }
```

2023-06-19 10:10 UTC, Kang-kyunghun commented on donghyeun/models/postDao.js
> +  });
initialize()는 서버가 실행 될 때만 진행되게 해주세요.

2023-06-19 10:10 UTC, Kang-kyunghun commented on donghyeun/routes/postRouter.js
> +router.post("/like/:postId", postController.Like);
endpoint 만들 때 동사는 사용하지 않습니다. 행위는 http method로 나타냅니다.
```suggestion
router.post("", postController.Upload);
router.get("/all", postController.All);
router.get("/user/:userId", postController.User);
router.patch("/:postId", postController.Modify);
router.delete("/:postId", postController.Delete);
router.post("/like/:postId", postController.Like);
```

2023-06-19 10:10 UTC, Kang-kyunghun commented on donghyeun/services/postService.js
> +
여기도 함수명 한 번 더 확인해 주세요

2023-06-20 02:43 UTC, kyeongraekim requested changes

2023-06-20 02:43 UTC, kyeongraekim commented on donghyeun/models/postDao.js
> +  , posts.content postingContent
- 개인적으로 다양한 코드를 보아왔지만 쉼표가 뒤에 붙어있는 컨벤션을 본적이 없는 것 같네요. 해당 내용의 쉼표 구분은 한 번 다시 재고해주세요!

2023-06-20 02:43 UTC, kyeongraekim commented on donghyeun/models/postDao.js
> +  , posts.content postingContent
- 해당 내용은 전체적으로 SQL 문을 살펴봐주시면서 검토를 해주세요!

2023-06-20 02:43 UTC, kyeongraekim commented on donghyeun/models/postDao.js
> +  , posts.content postingContent
```suggestion
  SELECT 
    posts.user_id userID,
    users.profile_image userProfileImage,
    posts.id postingId,
    posts.imageurl postingImageUrl,
    posts.content postingContent,
    ... 이하생략
```

2023-06-20 02:43 UTC, kyeongraekim commented on donghyeun/models/postDao.js
> +const DeletePost = async (postId) => {
- node.js 자바스크립트 환경에서의 클래스가 아닌 함수 변수명은 소문자로 시작하여주세요!

2023-06-20 02:43 UTC, kyeongraekim commented on donghyeun/models/postDao.js
> +const DeletePost = async (postId) => {
- 또한 deletePostById와 같이 정확히 어떠한 기준점으로 해당 데이터 리소스를 삭제하는것인지 명시해주세요!

2023-06-20 02:43 UTC, kyeongraekim commented on donghyeun/models/postDao.js
> +const getUserPost = async (userId) => {
- 이곳도 getPostById와 같은 의미로 클린한 변수명을 선정해주세요!

2023-06-20 02:43 UTC, kyeongraekim commented on donghyeun/routes/index.js
> +router.use("/posts", postRouter.router);
- 보다 클린한 코드 형태를 위하여, 해당 require 문은 가장윗단에서 선언하여 주시고, 실제 활용은 아래에 따로 영역분리르 하여주세요!

```suggestion
const userRouter = require("./userRouter");
const postRouter = require("./postRouter");

router.use("/users", userRouter.router);
router.use("/posts", postRouter.router);
```

2023-06-21 10:07 UTC, merged