[이주현] Assignment 1 Project Layered pattern 적용
wecode-bootcamp-korea/47-backend-westagram-2 pull request #18
Opened 2023-06-19 08:54 UTC by sioscorial

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 레이어드 패턴으로 변경

<br />

## :: 구현 사항 설명 - 레이어드 패턴으로 변경

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-06-19 10:14 UTC, Kang-kyunghun requested changes

2023-06-19 10:14 UTC, Kang-kyunghun commented on joohyun/app.js
> +const http = require("http");
```suggestion
```

2023-06-19 10:14 UTC, Kang-kyunghun commented on joohyun/app.js
> +const server = http.createServer(app);
http 모듈은 굳이 사용하지 않아도 됩니다.
```suggestion
```

2023-06-19 10:14 UTC, Kang-kyunghun commented on joohyun/app.js
> +    console.error(err);
```suggestion
const start = async () => {
  try {
    app.listen(PORT, () => console.log(`Server is listening on ${PORT}`));
  } catch (err) {
    console.error(err);
```

2023-06-19 10:14 UTC, Kang-kyunghun commented on joohyun/controllers/postController.js
> +  if (!title || !content || !userId) {
```suggestion
  const { title, content, userId } = req.body;
  
  if (!title || !content || !userId) {
```

2023-06-20 02:35 UTC, kyeongraekim requested changes

2023-06-20 02:35 UTC, kyeongraekim commented on joohyun/controllers/postController.js
> +const postsLikes = async (req, res) => {
- 이곳도 위의 워딩 명칭과 통일 시켜서 create라는 동적 단어를 사용하셔도 좋을 것 같네요!

2023-06-20 02:35 UTC, kyeongraekim commented on joohyun/models/postDao.js
> +const createPosts = async (title, content, userId) => {
- 현재 에러 핸들링이 Controller 유저 단에서만 적용이 되어있네요!
- try-catch 를 이용하여 MySQL이 발생시킬 수 있는 온갖 다양한 (미리 예측하지 못할 수 있는) 에러들을 어플리케이션 단에서 핸들링 할 수 있게, try-catch 문을 DAO 내 전체 모듈에 적용시켜보세요!

2023-06-20 02:35 UTC, kyeongraekim commented on joohyun/routes/postRouter.js
> +router.post("/like/:userId/:postId", postController.postsLikes);
- RESTful 한 엔드포인트 설계법에서는 슬래쉬 구분자로 데이터의 의미적인 영역을 점점 축소해나갑니다. 따라서
- /like/:userId/post/:postId 정도로의 표현이 이루어져야할 것 같네요!
- 다만 추후 배우실 인증인가 코드에서 userId의 path parameter 표현이 불필요하다는 것을 배우실 예정이지 참고해주세요!

2023-06-20 02:35 UTC, kyeongraekim commented on joohyun/services/userService.js
> +  // password validation using REGEX
- 코드 독해로 의미 파악이 충분히 가득한 주석은 상용화될 main 으로의 코드 푸시 전 필히 삭제하여주세요!

2023-06-20 09:43 UTC, Kang-kyunghun requested changes

2023-06-20 09:43 UTC, Kang-kyunghun commented on joohyun/models/postDao.js
> +  console.log(selectResult);
불필요한 콘솔은 제거해 주세요.

2023-06-21 10:08 UTC, merged