Feature/seongnam assignment layer pattern
wecode-bootcamp-korea/47-backend-westagram-2 pull request #19
Opened 2023-06-20 01:31 UTC by jseongnam

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 리팩토링

<br />

## :: 구현 목표 - layerPattern 구조에 맞게 코드 리팩토링

<br />

## :: 구현 사항 설명 - 각 구현 사항들을, data, fixdata, post, user로 나누어 구현하였습니

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![image](https://github.com/wecode-bootcamp-korea/47-backend-westagram-2/assets/105405028/2d2d3d98-586f-40be-a1ee-a523da16c6bd)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지

![image](https://github.com/wecode-bootcamp-korea/47-backend-westagram-2/assets/105405028/b2cbddab-8760-4dd8-8949-4bf0d5c6668c)

3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
![image](https://github.com/wecode-bootcamp-korea/47-backend-westagram-2/assets/105405028/b0742507-4b47-4f7f-9bef-ff56744eb351)

<br />

## :: 기타 질문 및 특이 사항
- 제가 짠 구조가 맞는지 궁금합니다.
- 이 구조로 짤 떄, 어떻게 req.param를 받아올 수 있는지 궁금합니다. 여기서 req.params는 routes/fixDataRouter.js 의 :userid 부분입니다.

2023-06-20 06:56 UTC, Kang-kyunghun requested changes
1. 파일을 구분 할 때는 큰 자원을 기준으로 나눕니다.(userController, postController, likeController 등)
2.전반적으로 함수 이름이 모호합니다. 함수 이름은 정화기 어떤 데이터에 대해서 어떠한 행위를 할 것인지 나타나면 좋을 것 같습니다.(createUser, getPostList, modifyUser 등)

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/app.js
> +const http = require("http");
```suggestion
```

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/app.js
> +const server = http.createServer(app);
굳이 http 모듈을 사용할 필요는 없습니다.
```suggestion
```

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/app.js
> +        server.listen(PORT, () => console.log(`Server is listening on ${PORT}`))
```suggestion
        app.listen(PORT, () => console.log(`Server is listening on ${PORT}`))
```

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/controllers/DataNumberController.js
> +const fixDatas2 = async(req,res)=>{
함수이름은 정확히 어떤 행위를 하는지 나타내 주세요.
```suggestion
const fixUser = async(req,res)=>{
```

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/controllers/DataNumberController.js
> +//controller/dataController.js
파일명도 dataController인데, 정확이 어떤 자원에 대한 controller인지 알 수가 없습니다.

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/routes/index.js
> +module.exports = router;
```suggestion
const fixDataRouter = require("./fixDataRouter");

router.use("/users", userRouter.router);
router.use("/posts", postRouter.router);
router.use("/datas", dataRouter.router);
router.use("/fixDatas",fixDataRouter.router);

module.exports = router;
```

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/controllers/postController.js
> +        if(!data.content || !data.user_id){
```suggestion
        const data = req.body;
        
        if(!data.content || !data.user_id){
```

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/controllers/userController.js
> +        return res.status(201).json({message : "SIGNUP_SUCCESS"});
```suggestion
        const data = req.body;
        
        if(!data.name || !data.email || !data.password){
            return res.status(400).json({message : 'KEY_ERROR'});
        }
        
        await userService.signUp(data.name,data.email,data.password);
        return res.status(201).json({message : "SIGNUP_SUCCESS"});
```

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/models/dataDao.js
> +})
데이터소스 코드가 중복 되고 있습니다. 해당 코드가 중복되지 않게 dataSource.js 파일을 만들어서 관리해 주세요.

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/models/dataDao.js
> +    });
initialize()는 서버가 실행 될 때만 진행되게 해주세요.

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/models/dataDao.js
> +// console.log(1);
불필요한 console.log 및 주석은 삭제해 주세요.

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/models/dataDao.js
> +        error.statusCode = 500;
상태코드 500은 내가 예외처리를 안 했다는 의미를 가질 수 있습니다. 따라서 500이 아닌 400 코드를 사용해 주세요.
여기 뿐만 아니라 다른 곳에서 500을 쓴 곳이 있습니다. 전체적으로 확인하고 수정해 주세요.

2023-06-20 06:56 UTC, Kang-kyunghun commented on seongnam/models/dataDao.js
> +// console.log(2);
여기 저기 불필요한 console.log 및 주석이 있네요. 전부 확인하고 삭제해 주세요.

2023-06-20 10:18 UTC, jseongnam reviewed
피드백 해주신 대로 코드 수정 및, 남은 기능들 구현하였습니다. 피드백 부탁드립니다.

2023-06-21 02:00 UTC, Kang-kyunghun requested changes

2023-06-21 02:00 UTC, Kang-kyunghun commented on seongnam/controllers/fixDataController.js
> +        console.log("userId:",userId);
PR은 다른 사람들과 같이 사용 되고, 기준인 되는 branch에 본인의 코드를 더하겠다는 요구를 신청하는 것입니다.
그렇기 때문에 불필요한 log나 주석은 제거하고 올려주셔야 합니다.

2023-06-21 02:00 UTC, Kang-kyunghun commented on seongnam/controllers/userController.js
> +        await userService.signUpService(data.name,data.email,data.password);
```suggestion
        const data = req.body;
        
        if(!data.name || !data.email || !data.password){
            return res.status(400).json({message : 'KEY_ERROR'});
        }
        
        await userService.signUpService(data.name,data.email,data.password);
```

2023-06-21 02:01 UTC, Kang-kyunghun commented
전체적으로 파일 구조 및 파일이름, 함수 이름 확인해 주세요

2023-06-21 06:06 UTC, jseongnam reviewed
말씀하신 변경해야할 사항 모두 변경했습니다.
파일 구조 변경, 변수 명 변경 했습니다.

2023-06-21 10:11 UTC, merged