[신동현] Assignment 2: Express API - 유저 회원가입 하기
wecode-bootcamp-korea/47-backend-westagram-2 pull request #3
Opened 2023-06-14 05:34 UTC by donghyeun02

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
<img width="871" alt="스크린샷 2023-06-14 오후 2 30 38" src="https://github.com/wecode-bootcamp-korea/47-backend-westagram-2/assets/129716523/5e13ceb8-54f3-444b-ad50-aabe27ec62e4">

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="1212" alt="스크린샷 2023-06-14 오후 2 23 29" src="https://github.com/wecode-bootcamp-korea/47-backend-westagram-2/assets/129716523/14a4e926-3adb-481e-bbb5-7e612b936c95">
<img width="1212" alt="스크린샷 2023-06-14 오후 2 23 29" src="https://github.com/wecode-bootcamp-korea/47-backend-westagram-2/assets/129716523/3f1db377-63af-4388-a0ff-9d8b633c5525">

3. DB 작업 PR인 경우 Table 생성 및 수정 결과에
<img width="959" alt="스크린샷 2023-06-14 오후 2 32 46" src="https://github.com/wecode-bootcamp-korea/47-backend-westagram-2/assets/129716523/78e201fe-7d27-4b4d-aa1a-787514dbd067">
 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-06-14 06:54 UTC, kyeongraekim requested changes

2023-06-14 06:54 UTC, kyeongraekim commented on donghyeun/app.js
> +// SELECT id, email, name, nickname, password, phone_number FROM users;
- 코드 진행에 불필요한 내용은 상용화될 main으로의 push에서 꼭 삭제해주시는 습관을 들여주세요!

2023-06-14 06:54 UTC, kyeongraekim commented on donghyeun/app.js
> +app.get("/users", async (req, res, next) => {
- 현재 next() 메소드를 사용하지 않는 기획임으로 해당 parameter에 선언해 줄 필요는 없어 보입니다!

2023-06-14 06:54 UTC, kyeongraekim commented on donghyeun/app.js
> +app.get("/users", async (req, res, next) => {
- 또한 회원가입 기능만을 담는 브랜치의 내용으로는 유저의 회원 정보를 조회하는 해당 코드의 기능이 불필요해보이네요!
- 실무에서는 내가 올려야 하는 특정 기능을 브랜치별로 엄격하게 분리 관리하는 모습이 필수 이오니, 해당 내용을 이번 과제를 통해서 연습해보세요!

2023-06-14 06:54 UTC, kyeongraekim commented on donghyeun/app.js
> +  console.log(req.body);
- 불필요한 콘솔로깅은 푸시전에 꼭 삭제해주시는 것을 습관화해주세요!

2023-06-14 06:54 UTC, kyeongraekim commented on donghyeun/app.js
> +  const { email, name, password, phone_number } = req.body;
Javascript Node.js 환경에서의 변수명은 camelCase로 관리해주셔야 합니다.
현재 snake_case로 되어 있는 내용을 수정해주세요!

2023-06-14 06:54 UTC, kyeongraekim commented on donghyeun/db/migrations/20230613112828_create_posts_table.sql
> +    user_id INT NOT NULL,
- user_id로서 칼럼이 존재하면 외래키의 기능을 담아야할 것 같아 보이는데 해당 내용이 생략되어 보이네요!

2023-06-14 06:58 UTC, kyeongraekim requested changes

2023-06-14 06:58 UTC, kyeongraekim commented on donghyeun/app.js
> +  res.json({ message: "userCreated" });
- 데이터가 생성됬을 때에 리턴값으로 마땅히 전송해야하는 http 상태코드 (201)를 리스폰스 시에 함께 전달해주세요!

2023-06-15 01:45 UTC, Kang-kyunghun requested changes

2023-06-15 01:45 UTC, Kang-kyunghun commented on donghyeun/db/migrations/20230614062000_create_likes_table.sql
> +    post_id INT NOT NULL,
해당 부분도 외래키 지정해 주세요.

2023-06-15 02:38 UTC, kyeongraekim requested changes

2023-06-15 02:38 UTC, kyeongraekim commented on donghyeun/db/migrations/20230614062000_create_likes_table.sql
> +);
- 보통 SNS나 게시글에 달리는 좋아요 기능은 한 명의 유저가 한 개의 게시글에 중복 좋아요를 할 수 없는 구조 입니다.
- 두 번 좋아요를 클릭하게 되면 해당 좋아요를 취소하는 절차로 적용이 되는데, 이러한 비즈니스 로직이 데이터베이스에서도 데이터로서 잘못된 데이터가 들어오지 않게 미리 막아두는 장치를 설정해야 합니다.
- user_id, post_id의 중복 기입을 막는 SQL unique constraint 명령문을 찾아서 적용해보세요!
- 해당 내용은 user_id 컬럼과 post_id 컬럼이 각 컬럼별로 별도로 고유값을 지녀야하는 모습이 아닌, 해당 컬럼이 동시에 중복값을 얻어내지 못하는 구조로 설정되어야 합니다.

2023-06-15 02:38 UTC, kyeongraekim commented on donghyeun/db/migrations/20230614062000_create_likes_table.sql
> +);
- 아래의 내용을 Alter Table에 추가하여주세요!

```javascript

    CONSTRAINT unique_user_post UNIQUE (user_id, post_id)

2023-06-15 05:06 UTC, kyeongraekim approved these changes

2023-06-15 05:06 UTC, merged